#! /system/bin/bash

#   Smurfed Out Tweaks
#     Created By Papa Smurf151 from XDA
# Governor Tweaks

. /system/etc/SmurfMod_settings.sh

if [ $governor_tweaks -eq 1 ]; then
	busybox mount -o remount,rw /system

	# Ondemand
	# ==============================================================

		if [ -e /sys/devices/system/cpu/cpu0/cpufreq/ondemand/up_threshold ]; then
			chmod -R 777 /sys/devices/system/cpu/cpufreq/ondemand
			echo "95" > /sys/devices/system/cpu/cpu0/cpufreq/ondemand/up_threshold;
			echo "5" > /sys/devices/system/cpu/cpu0/cpufreq/ondemand/down_differential;
			echo "1" > /sys/devices/system/cpu/cpu0/cpufreq/ondemand/io_is_busy;
			echo "1" > /sys/devices/system/cpu/cpu0/cpufreq/ondemand/sampling_down_factor;
			echo "120000" > /sys/devices/system/cpu/cpu0/cpufreq/ondemand/sampling_rate;
			chmod -R 444 /sys/devices/system/cpu/cpufreq/ondemand
		fi;		
		if [ -e /sys/devices/system/cpu/cpu1/cpufreq/ondemand/up_threshold ]; then
			chmod -R 777 /sys/devices/system/cpu/cpufreq/ondemand
			echo "95" > /sys/devices/system/cpu/cpu1/cpufreq/ondemand/up_threshold;
			echo "5" > /sys/devices/system/cpu/cpu1/cpufreq/ondemand/down_differential;
			echo "1" > /sys/devices/system/cpu/cpu1/cpufreq/ondemand/io_is_busy;
			echo "1" > /sys/devices/system/cpu/cpu1/cpufreq/ondemand/sampling_down_factor;
			echo "120000" > /sys/devices/system/cpu/cpu1/cpufreq/ondemand/sampling_rate;
			chmod -R 444 /sys/devices/system/cpu/cpufreq/ondemand
		fi;
		if [ -e /sys/devices/system/cpu/cpufreq/ondemand/up_threshold ]; then
			chmod -R 777 /sys/devices/system/cpu/cpufreq/ondemand
			echo "95" > /sys/devices/system/cpu/cpufreq/ondemand/up_threshold;
			echo "5" > /sys/devices/system/cpu/cpufreq/ondemand/down_differential;
			echo "1" > /sys/devices/system/cpu/cpufreq/ondemand/io_is_busy;
			echo "1" > /sys/devices/system/cpu/cpufreq/ondemand/sampling_down_factor;
			echo "120000" > /sys/devices/system/cpu/cpufreq/ondemand/sampling_rate;
			chmod -R 444 /sys/devices/system/cpu/cpufreq/ondemand
		fi;

	# ==============================================================
	# OndemandX
	# ==============================================================

		if [ -e /sys/devices/system/cpu/cpu0/cpufreq/ondemandx/up_threshold ]; then
			chmod -R 777 /sys/devices/system/cpu/cpufreq/ondemandx
			echo "90" > /sys/devices/system/cpu/cpu0/cpufreq/ondemandx/up_threshold;
			echo "5" > /sys/devices/system/cpu/cpu0/cpufreq/ondemandx/down_differential;
			echo "1" > /sys/devices/system/cpu/cpu0/cpufreq/ondemandx/io_is_busy;
			echo "1" > /sys/devices/system/cpu/cpu0/cpufreq/ondemandx/sampling_down_factor;
			echo "120000" > /sys/devices/system/cpu/cpu0/cpufreq/ondemandx/sampling_rate;
			chmod -R 444 /sys/devices/system/cpu/cpufreq/ondemandx
		fi;
		if [ -e /sys/devices/system/cpu/cpu1/cpufreq/ondemandx/up_threshold ]; then
			chmod -R 777 /sys/devices/system/cpu/cpufreq/ondemandx
			echo "90" > /sys/devices/system/cpu/cpu1/cpufreq/ondemandx/up_threshold;
			echo "5" > /sys/devices/system/cpu/cpu1/cpufreq/ondemandx/down_differential;
			echo "1" > /sys/devices/system/cpu/cpu1/cpufreq/ondemandx/io_is_busy;
			echo "1" > /sys/devices/system/cpu/cpu1/cpufreq/ondemandx/sampling_down_factor;
			echo "120000" > /sys/devices/system/cpu/cpu1/cpufreq/ondemandx/sampling_rate;
			chmod -R 444 /sys/devices/system/cpu/cpufreq/ondemandx
		fi;
		if [ -e /sys/devices/system/cpu/cpufreq/ondemandx/up_threshold ]; then
			chmod -R 777 /sys/devices/system/cpu/cpufreq/ondemandx
			echo "90" > /sys/devices/system/cpu/cpufreq/ondemandx/up_threshold;
			echo "5" > /sys/devices/system/cpu/cpufreq/ondemandx/down_differential;
			echo "1" > /sys/devices/system/cpu/cpufreq/ondemandx/io_is_busy;
			echo "1" > /sys/devices/system/cpu/cpufreq/ondemandx/sampling_down_factor;
			echo "120000" > /sys/devices/system/cpu/cpufreq/ondemandx/sampling_rate;
			chmod -R 444 /sys/devices/system/cpu/cpufreq/ondemandx
		fi;

	# ==========================================================
	# Conservative 
	# ==========================================================

		if [ -e /sys/devices/system/cpu/cpu0/cpufreq/conservative/up_threshold ]; then
			chmod -R 777 /sys/devices/system/cpu/cpufreq/conservative
			echo "95" > /sys/devices/system/cpu/cpu0/cpufreq/conservative/up_threshold;
			echo "40" > /sys/devices/system/cpu/cpu0/cpufreq/conservative/down_threshold; # 35 # 12 # 30 (higher will lead to noticable lags) # 35 # screen off: # 50 ## 35
			echo "10" > /sys/devices/system/cpu/cpu0/cpufreq/conservative/freq_step; # more aggressive ramping up (50) # screen off: # 10
			echo "120000" > /sys/devices/system/cpu/cpufreq/conservative/sampling_rate;
			echo "1" > /sys/devices/system/cpu/cpufreq/conservative/sampling_down_factor;
			chmod -R 444 /sys/devices/system/cpu/cpufreq/conservative
		fi;
		if [ -e /sys/devices/system/cpu/cpu1/cpufreq/conservative/up_threshold ]; then
			chmod -R 777 /sys/devices/system/cpu/cpufreq/conservative
			echo "95" > /sys/devices/system/cpu/cpu1/cpufreq/conservative/up_threshold;
			echo "40" > /sys/devices/system/cpu/cpu1/cpufreq/conservative/down_threshold; # 35 # 12 # 30 (higher will lead to noticable lags) # 35 # screen off: # 50 ## 35
			echo "10" > /sys/devices/system/cpu/cpu1/cpufreq/conservative/freq_step; # more aggressive ramping up (50) # screen off: # 10
			echo "120000" > /sys/devices/system/cpu/cpufreq/conservative/sampling_rate;
			echo "1" > /sys/devices/system/cpu/cpufreq/conservative/sampling_down_factor;
			chmod -R 444 /sys/devices/system/cpu/cpufreq/conservative
		fi;
		if [ -e /sys/devices/system/cpu/cpufreq/conservative/up_threshold ]; then
			chmod -R 777 /sys/devices/system/cpu/cpufreq/conservative
			echo "95" > /sys/devices/system/cpu/cpufreq/conservative/up_threshold;
			echo "40" > /sys/devices/system/cpu/cpufreq/conservative/down_threshold; # 35 # 12 # 30 (higher will lead to noticable lags) # 35 # screen off: # 50 ## 35
			echo "10" > /sys/devices/system/cpu/cpufreq/conservative/freq_step; # more aggressive ramping up (50) # screen off: # 10
			echo "120000" > /sys/devices/system/cpu/cpufreq/conservative/sampling_rate;
			echo "1" > /sys/devices/system/cpu/cpufreq/conservative/sampling_down_factor;
			chmod -R 444 /sys/devices/system/cpu/cpufreq/conservative
		fi;

	# ==============================================================
	# lulzactive 
	# ==============================================================

		if [ -e /sys/devices/system/cpu/cpufreq/lulzactive/inc_cpu_load ]; then
			chmod -R 777 /sys/devices/system/cpu/cpufreq/lulzactive
			echo "90" > /sys/devices/system/cpu/cpufreq/lulzactive/inc_cpu_load;
			if [ "`cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq`" -eq 200000 ] && [ "`cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq`" -eq 1200000 ]; then
				echo "4" > /sys/devices/system/cpu/cpufreq/lulzactive/pump_up_step;
			elif [ "`cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq`" -eq 200000 ] && [ "`cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq`" -eq 1400000 ]; then 
				echo "5" > /sys/devices/system/cpu/cpufreq/lulzactive/pump_up_step;
			elif [ "`cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq`" -eq 200000 ] && [ "`cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq`" -eq 1600000 ]; then 
				echo "6" > /sys/devices/system/cpu/cpufreq/lulzactive/pump_up_step;
			elif [ "`cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq`" -eq 100000 ] && [ "`cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq`" -eq 1200000 ]; then 
				echo "5" > /sys/devices/system/cpu/cpufreq/lulzactive/pump_up_step;
			elif [ "`cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq`" -eq 100000 ] && [ "`cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq`" -eq 1400000 ]; then 
				echo "6" > /sys/devices/system/cpu/cpufreq/lulzactive/pump_up_step;
			elif [ "`cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq`" -eq 100000 ] && [ "`cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq`" -eq 1600000 ]; then 
				echo "7" > /sys/devices/system/cpu/cpufreq/lulzactive/pump_up_step;
			elif [ "`cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq`" -eq 100000 ] && [ "`cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq`" -eq 800000 ]; then 
				echo "3" > /sys/devices/system/cpu/cpufreq/lulzactive/pump_up_step;
			elif [ "`cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq`" -eq 100000 ] && [ "`cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq`" -eq 1000000 ]; then 
				echo "4" > /sys/devices/system/cpu/cpufreq/lulzactive/pump_up_step;
			elif [ "`cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq`" -eq 200000 ] && [ "`cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq`" -eq 800000 ]; then 
				echo "2" > /sys/devices/system/cpu/cpufreq/lulzactive/pump_up_step;
			elif [ "`cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq`" -eq 200000 ] && [ "`cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq`" -eq 1000000 ]; then 
				echo "3" > /sys/devices/system/cpu/cpufreq/lulzactive/pump_up_step;
			fi;
			echo "1" > /sys/devices/system/cpu/cpufreq/lulzactive/pump_down_step;
			echo "6" > /sys/devices/system/cpu/cpufreq/lulzactive/screen_off_min_step;
			echo "2" > /sys/devices/system/cpu/cpufreq/lulzactive/pump_down_step
			echo "50000" > /sys/devices/system/cpu/cpufreq/lulzactive/up_sample_time
			echo "40000" > /sys/devices/system/cpu/cpufreq/lulzactive/down_sample_time
			chmod -R 444 /sys/devices/system/cpu/cpufreq/lulzactive
		fi;

	# ==============================================================
	# smartassV2 
	# ==============================================================

		if [ -e /sys/devices/system/cpu/cpufreq/smartass/awake_ideal_freq ]; then
			chmod -R 777 /sys/devices/system/cpu/cpufreq/smartass
			echo "500000" > /sys/devices/system/cpu/cpufreq/smartass/awake_ideal_freq;
			if [ "`cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq`" -eq 200000 ]; then
				echo "200000" > /sys/devices/system/cpu/cpufreq/smartass/sleep_ideal_freq;
			else
				echo "200000" > /sys/devices/system/cpu/cpufreq/smartass/sleep_ideal_freq;
			fi;
			echo "500000" > /sys/devices/system/cpu/cpufreq/smartass/sleep_wakeup_freq;
			echo "85" > /sys/devices/system/cpu/cpufreq/smartass/max_cpu_load;
			echo "75" > /sys/devices/system/cpu/cpufreq/smartass/min_cpu_load;
			echo "200000" > /sys/devices/system/cpu/cpufreq/smartass/ramp_down_step;
			echo "200000" > /sys/devices/system/cpu/cpufreq/smartass/ramp_up_step;
			echo "48000" > /sys/devices/system/cpu/cpufreq/smartass/up_rate_us;
			echo "49000" > /sys/devices/system/cpu/cpufreq/smartass/down_rate_us;
			chmod -R 444 /sys/devices/system/cpu/cpufreq/smartass
		fi;

	# ==============================================================
	# interactive 
	# ==============================================================

		if [ -e /sys/devices/system/cpu/cpufreq/interactive/go_hispeed_load ] ; then
			chmod -R 777 /sys/devices/system/cpu/cpufreq/interactive
			echo "95" > /sys/devices/system/cpu/cpufreq/interactive/go_hispeed_load
			echo "1000000" > /sys/devices/system/cpu/cpufreq/interactive/hispeed_freq
			echo "10000" > /sys/devices/system/cpu/cpufreq/interactive/min_sample_time
			echo "40000" > /sys/devices/system/cpu/cpufreq/interactive/timer_rate
			chmod -R 777 /sys/devices/system/cpu/cpufreq/interactive
		fi;
	busybox mount -o remount,ro /system
fi