#! /system/bin/bash

#   Smurfed Out Tweaks
#     Created By Papa Smurf151 from XDA
# Remove Main Log

. /system/etc/SmurfMod_settings.sh

if [ $remove_logcatting -eq 1 ]; then
	busybox mount -o remount,rw /system
	if [ -e /dev/log/main ]; then
		cp -f /dev/log/main /sdcard/SmurfedBackups/main
		rm -f /dev/log/main
	fi
	busybox mount -o remount,rw /system
fi

if [ $remove_logcatting -eq 0 ]; then
	busybox mount -o remount,rw /system
	if [ ! -e /dev/log/main ]; then
		cp -f /sdcard/SmurfedBackups/main /dev/log/main
	fi
	busybox mount -o remount,rw /system
fi