#! /system/bin/bash

#   Smurfed Out Tweaks
#     Created By Papa Smurf151 from XDA
# Fix Permissions

. /system/etc/SmurfMod_settings.sh

if [ $fix_permissions -eq 1 ]; then
	busybox mount -o remount,rw /system
	START=` busybox date +%s `
		PKGLINE=(` pm list packages -f | busybox cut -d ':' -f2 `);
		MAX=${#PKGLINE[*]}
		INCREMENT=5
		PROGRESS=0
		PROGRESS_BAR=""
		echo
		echo "Fixing permissions..."
		echo
		for pkgline in ${PKGLINE[*]}; do
			PKGNAME=` echo $pkgline | busybox cut -d '=' -f2 `
			CODEPATH=` echo $pkgline | busybox cut -d '=' -f1 `
			DATAPATH=/data/data/$PKGNAME
			PKGUID=` busybox grep $CODEPATH /data/system/packages.xml | busybox sed 's%.*serId="\(.*\)".*%\1%' |  busybox cut -d '"' -f1 `
			let PROGRESS++
			PERCENT=$(( $PROGRESS * 100 / $MAX ))
			if busybox [ $PERCENT -eq $INCREMENT ]; then
				INCREMENT=$(( $INCREMENT + 5 ))
				PROGRESS_BAR="${PROGRESS_BAR}="
			fi
			echo -ne "  \r  ${PROGRESS}/${MAX} ${PERCENT}% [ ${PROGRESS_BAR}> ]"
			if busybox [ -e $CODEPATH ]; then
				APPDIR=` busybox dirname $CODEPATH `
				if busybox [ $APPDIR = /system/app ]; then
					busybox chown 0 $CODEPATH
					busybox chown :0 $CODEPATH
					busybox chmod 644 $CODEPATH
				elif busybox [ $APPDIR = /data/app ]; then
					busybox chown 1000 $CODEPATH
					busybox chown :1000 $CODEPATH
					busybox chmod 644 $CODEPATH
				elif busybox [ $APPDIR = /data/app-private ]; then
					busybox chown 1000 $CODEPATH
					busybox chown :$PKGUID $CODEPATH
					busybox chmod 640 $CODEPATH
				fi
				if busybox [ -d $DATAPATH ]; then
					busybox chmod 755 $DATAPATH
					busybox chown $PKGUID $DATAPATH
					busybox chown :$PKGUID $DATAPATH
					DIRS=` busybox find $DATAPATH -mindepth 1 -type d `
					for file in $DIRS; do
						PERM=755
						NEWUID=$PKGUID
						NEWGID=$PKGUID
						FNAME=` busybox basename $file `
						case $FNAME in
							lib)
								busybox chmod 755 $file
								NEWUID=1000
								NEWGID=1000
								PERM=755
							;;
							shared_prefs)
								busybox chmod 771 $file
								PERM=660					
							;;
							databases)
								busybox chmod 771 $file
								PERM=660
							;;
							cache)
								busybox chmod 771 $file
								PERM=600
							;;
							*)
								busybox chmod 771 $file
								PERM=771
							;;
						esac
						busybox chown $NEWUID $file
						busybox chown :$NEWGID $file
						busybox find $file -type f -maxdepth 1 ! -perm $PERM -exec busybox chmod $PERM {} ';'
						busybox find $file -type f -maxdepth 1 ! -user $NEWUID -exec busybox chown $NEWUID {} ';'
						busybox find $file -type f -maxdepth 1 ! -group $NEWGID -exec busybox chown :$NEWGID {} ';'
					done
				fi
			fi
		done
		sync
		STOP=` busybox date +%s `
		RUNTIME=` runtime $START $STOP `
		echo
		echo
		echo "Fix permissions complete! Runtime: ${RUNTIME}"
		echo
		busybox mount -o remount,ro /system
fi